export default selectedMusicDB = {
  name: 'Data',
  properties: {
    wrapperType: 'string',
    kind: 'string',
    artistId: 'int',
    collectionId: 'int',
    trackId: 'int',
    artistName: 'string',
    collectionName: 'string',
    trackName: 'string',
    collectionCensoredName: 'string',
    trackCensoredName: 'string',
    artistViewUrl: 'string',
    collectionViewUrl: 'string',
    trackViewUrl: 'string',
    previewUrl: 'string',
    artworkUrl30: 'string',
    artworkUrl60: 'string',
    artworkUrl100: 'string',
    collectionPrice: 'float',
    trackPrice: 'float',
    releaseDate: 'string',
    collectionExplicitness: 'string',
    trackExplicitness: 'string',
    discCount: 'int',
    discNumber: 'int',
    trackCount: 'int',
    trackNumber: 'int',
    trackTimeMillis: 'int',
    country: 'string',
    currency: 'string',
    primaryGenreName: 'string',
    isStreamable: 'bool',
  },
  primaryKey: 'trackId',
};
